---
# Copyright (C) 2019 Leonardo Bechea <leonardo.bechea@innobyte.com>
# Copyright (C) 2019 Alin Alexandru <alin.alexandru@innobyte.com>
# Copyright (C) 2019 DebOps <https://debops.org/>
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Manage Grafana
  hosts: [ 'debops_service_grafana' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::grafana' ]
      keyring__dependent_apt_keys:
        - '{{ grafana__keyring__dependent_apt_keys }}'

    - role: etc_services
      tags: [ 'role::etc_services', 'skip::etc_services' ]
      etc_services__dependent_list:
        - '{{ grafana__etc_services__dependent_list }}'

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ grafana__ferm__dependent_rules }}'
        - '{{ nginx__ferm__dependent_rules if (grafana__nginx_enabled|bool) else [] }}'

    - role: python
      tags: [ 'role::python', 'skip::python' ]
      python__dependent_packages3:
        - '{{ nginx__python__dependent_packages3 }}'
      python__dependent_packages2:
        - '{{ nginx__python__dependent_packages2 }}'

    - role: nginx
      tags: [ 'role::nginx', 'skip::nginx' ]
      nginx__dependent_upstreams:
        - '{{ grafana__nginx__dependent_upstreams }}'
      nginx__dependent_servers:
        - '{{ grafana__nginx__dependent_servers }}'
      when: grafana__nginx_enabled|bool

    - role: grafana
      tags: [ 'role::grafana', 'skip::grafana' ]
